"""add_required_consecutive_hours_to_class_subject_allocation

Revision ID: a33c0e17ef38
Revises: ebc5f9a610cb
Create Date: 2025-12-13 12:26:35.061937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33c0e17ef38'
down_revision: Union[str, None] = 'ebc5f9a610cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_subject_allocations', sa.Column('required_consecutive_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_subject_allocations', 'required_consecutive_hours')
    # ### end Alembic commands ###

