"""add_allow_multiple_in_one_day_to_class_subject_allocation

Revision ID: f0c0d15322f7
Revises: add_number_of_students_class
Create Date: 2025-12-13 11:36:22.605317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c0d15322f7'
down_revision: Union[str, None] = 'add_number_of_students_class'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_subject_allocations', sa.Column('allow_multiple_in_one_day', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_subject_allocations', 'allow_multiple_in_one_day')
    # ### end Alembic commands ###

